### PR TITLE
Add Darwinia and Crab address

### PR DESCRIPTION
**Pull request by furoxr**
Please add Darwinia and Crab network.
Thank you~

Related to: https://github.com/safe-global/safe-deployments/pull/254

### CODE REVIEW

**Comment by furoxr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by furoxr** [comment]
recheck

**Comment by Uxio0** [comment]
Could you rebase and fix conflicts?

**Comment by furoxr** [comment]
> Could you rebase and fix conflicts?

Thanks for remind, I have updated

**Pull request merged**
