### PR TITLE
Add WEMIX3.0 Mainnet & Testnet

### PR DESCRIPTION
**Pull request by comverser**

### CODE REVIEW

**Comment by Uxio0** [comment]
@comverser please accept the CLA 😉

**Comment by comverser** [comment]
recheck

**Comment by comverser** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by comverser** [comment]
I found typo mistake. Please let me fix it...

**Comment by Uxio0** [comment]
Do the block explorers you add share the same API as Etherscan? It doesn't look so

**Comment by comverser** [comment]
> Do the block explorers you add share the same API as Etherscan? It doesn't look so

@Uxio0, It is not the same API as Etherscan. However, I included it with the thought that it may support the Etherscan format in the future. Should I remove it from the list?

**Comment by Uxio0** [comment]
> @Uxio0, It is not the same API as Etherscan. However, I included it with the thought that it may support the Etherscan format in the future. Should I remove it from the list?

Yes please, when it supports etherscan API (or blockscout API) you can open a PR again

**Comment by comverser** [comment]
@Uxio0, I appreciate your feedback and I would like to let you know that I have made the correction.

**Comment by Uxio0** [comment]
Could you rebase and resolve conflicts?

**Pull request closed without merging**
