### PR TITLE
Adding network conflux mainnet and testnet

### PR DESCRIPTION
**Pull request by Pana**

### CODE REVIEW

**Comment by Pana** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Pana** [comment]
recheck

**Comment by Pana** [comment]
@fmrsabino Can you review this when you have time ?

**Comment by moisses89** [comment]
@Pana could you fix the errors? also run pre-commit to ensure to pass linter review.

**Review by moisses89 — CHANGES_REQUESTED** [review]
@Pana could you fix the errors? also run pre-commit to ensure to pass linter review.

**Comment by Pana** [comment]
> @Pana could you fix the errors? also run pre-commit to ensure to pass linter review.

Fixed

**Comment by moisses89** [comment]
@Pana this PR is still having linter issues.

**Comment by moisses89** [comment]
@Pana  safe_deployments was updated to 1.32.0, this PR will need also a rebase.

**Comment by moisses89** [comment]
Closing this issue due to inactivity, feel free to add the chain following the new process https://github.com/safe-global/safe-eth-py/pull/773#issuecomment-2077002586 this will automatically to verify the chain parameters and we will create a PR from that.

**Pull request closed without merging**
