### PR TITLE
add ethereumpow and ethereumfair

### PR DESCRIPTION
**Pull request by benjamintshi**
Network Name: Ethereum Pow
New RPC URL: https://mainnet.ethereumpow.org/
Chain ID: 10001
Currency Symbol (Optional): ETHW
Block Explorer URL: https://www.oklink.com/en/ethw/

Network Name: Ethereum Fair
New RPC URL: https://rpc.etherfair.org/
Chain ID: 513100
Currency Symbol (Optional): ETF
Block Explorer URL: https://explorer.etherfair.org/

### CODE REVIEW

**Comment by Uxio0** [comment]
We will not add these chains as Ethereum POW chainId 10001 is already taken (take a look at https://chainlist.org/)

**Comment by benjamintshi** [comment]
> 

thanks ,is there have another way to add EthereumPoW chainid

**Comment by Uxio0** [comment]
> > 
> 
> thanks ,is there have another way to add EthereumPoW chainid

Until they change their `chainId`, no

**Comment by moisses89** [comment]
@Uxio0 this PR is long ago opened and I seems that the chainID change was rejected, https://github.com/ethereum-lists/chains/pull/1602
Maybe we should be close this PR, what do you think?

**Pull request closed without merging**
