### PR TITLE
Fix cache memory leaks

### LINKED ISSUE #322: Memory leak in get_contracts function
**Describe the bug**
gnosis.safe.safe.Safe.get_contract is caching the results with @cache decorator that means that can storage memory without limit. 
```
    @cache
    def get_contract(self) -> Contract:
        v_1_3_0_contract = get_safe_V1_3_0_contract(self.w3, address=self.address)
        version = v_1_3_0_contract.functions.VERSION().call()
        if version == "1.3.0":
            return v_1_3_0_contract
        else:
            return get_safe_V1_1_1_contract(self.w3, address=self.address)
```
I noticied it working in https://github.com/safe-global/safe-transaction-service/issues/1008
**Expected behavior**
Don't storage in local memory without limits.

**Possible solutions**
- remove cache decorator
- configure time to live cache limiting the memory that could reach and defining a time to clean the cache.

### PR DESCRIPTION
**Pull request by Uxio0**
- `@cache` is stored in the Class, not in the Object. So when multiple `Safe` objects were created, and `get_contract()` was called, cache only increased (also if the same Safe was created multiple times)
- Use now `@cached_property`, which is binded to the object, so when the object is destroyed, so is the cached value
- Closes #322
- Related to #325
- All the credit to @moisses89 who was the one realising of this behaviour

### CODE REVIEW

**Comment by moisses89** [comment]
I would like to test something like this https://github.com/safe-global/safe-eth-py/pull/325/files#diff-dbf8b4d43e58fe9c2345cff856302940182d80b34590cfd26648a7076277d8c5R819 and also check that everything is ok with the memory from tx-service.

**Review by hectorgomezv — APPROVED** [review]
LGTM 🙂

**Review by moisses89 — COMMENTED** [review]
Should we continue reviewing the @cache decorator? For example this could generate other memory leak AFAIK. 
```
    @cache
    def get_chain_id(self) -> int:
        """
        :return: ChainId returned by the RPC `eth_chainId` method. It should never change, so it's cached.
        """
        return int(self.w3.eth.chain_id)
```

**Comment by Uxio0** [comment]
> Should we continue reviewing the @cache decorator? For example this could generate other memory leak AFAIK.
> 
> ```
>     @cache
>     def get_chain_id(self) -> int:
>         """
>         :return: ChainId returned by the RPC `eth_chainId` method. It should never change, so it's cached.
>         """
>         return int(self.w3.eth.chain_id)
> ```

Usually EthereumClient is created as a Singleton, so this is not an issue, but we should definitely review other places

**Pull request merged**
