### PR TITLE
add bitlayer testnet contract info

### PR DESCRIPTION
**Pull request by Zerppen**

### CODE REVIEW

**Comment by Zerppen** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by falvaradorodriguez** [comment]
Hi @Zerppen!

To add a new address you must follow these steps : [add-new-address-for-new-chains](https://github.com/safe-global/safe-eth-py?tab=readme-ov-file#add-new-address-for-new-chains)

"EthereumNetwork.Bitlayer_Testnet" does not exist in safe-eth-py and also other information is needed to be able to incorporate this. 

Please close this PR and open the corresponding issue.

Thank you.

**Review by falvaradorodriguez — CHANGES_REQUESTED** [review]
Hi @Zerppen !

To add a new address you must follow these steps: [add-new-address-for-new-chains](https://github.com/safe-global/safe-eth-py?tab=readme-ov-file#add-new-address-for-new-chains)

Bitlayer_Testnet is not a valid name and also other information is needed to be able to incorporate this. 

Please close this PR and open the corresponding issue.

Thank you.

**Comment by Zerppen** [comment]
I had issued at #882  check it pls

**Pull request closed without merging**
