### PR TITLE
Add Evmos Mainnet & Testnet

### PR DESCRIPTION
**Pull request by datradito**
Please add master-copies & proxy factory addresses to safe-eth-py. Thanks

### CODE REVIEW

**Comment by ElvisKrop** [comment]
> @ElvisKrop must sign the CLA too wink

Hello Uxío!
Could you please give the link to the CLA?
Unfortunately, Link from the CLA Assistant Lite bot is broken

**Comment by Uxio0** [comment]
> > @ElvisKrop must sign the CLA too wink
> 
> Hello Uxío! Could you please give the link to the CLA? Unfortunately, Link from the CLA Assistant Lite bot is broken

Thanks for pointing that out, we are working on it!

**Comment by Uxio0** [comment]
CLA is already in place, could you sign it and rebase?

**Comment by datradito** [comment]
Closing it to create a new one more cleaner.

**Comment by datradito** [comment]
Closing it to create a new one more cleaner.

**Pull request closed without merging**
