### PR TITLE
Add Shibarium 1.3.0 contracts

### PR DESCRIPTION
**Pull request by melnour**

### CODE REVIEW

**Comment by melnour** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by moisses89 — DISMISSED** [review]
Please add first the addresses on https://github.com/safe-global/safe-deployments/tree/main

**Comment by moisses89** [comment]
Looks like addresses were added her https://github.com/safe-global/safe-deployments/pull/360

**Comment by falvaradorodriguez** [comment]
Please resolve the conflicts first @melnour

**Comment by Uxio0** [comment]
@melnour I think by mistake you pushed a lot of commits, could you fix the PR? 😃

**Pull request closed without merging**
